apiVersion: batch/v1
kind: Job
metadata:
  name: "dbmigrations"
  namespace: development
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrations
          image: "00004.dkr.ecr.us-east-1.amazonaws.com/backend:3a32219eb9b60c71ea441260e5738ec697a0d26a"
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c", "npm run db-migrate" ]
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: PORT
            - name: BASIC_AUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: BASIC_AUTH_USERNAME
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: BASIC_AUTH_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_NAME