---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: development
spec:
  interval: 1m
  releaseName: backend
  chart:
    spec:
      chart: ./kubernetes/flux/development/backend/chart
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: backend-chart
        namespace: flux-system
  values:
    name: backend
    cluster: eks-development-us-east-1
    replicaCount: 2
    labels:
      app: backend
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    # livenessProbe:
    #   httpGet:
    #     path: /api/v1/api-docs
    #     port: http
    # readinessProbe:
    #   httpGet:
    #     path: /api/v1/api-docs
    #     port: http
    serviceAccount:
      create: true
      annotations: {}
      name: "backend"
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    service:
      type: NodePort
      port: 5000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:00004:certificate/662f825a-be2a-44d5-840b-a3ac1984a658
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/healthcheck-path: /api/v1/api-docs
      hosts:
        - host: backend.development.pintv.systems
          paths:
            - path: /
    image:
      repository: 00004.dkr.ecr.us-east-1.amazonaws.com/backend
      pullPolicy: Always
      tag: '3a32219eb9b60c71ea441260e5738ec697a0d26a'
    envFrom:
      - secretRef:
          name: backend-secrets