---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: production
spec:
  interval: 1m
  releaseName: backend
  chart:
    spec:
      chart: ./kubernetes/flux/production/backend/chart
      version: "0.1.0"
      sourceRef:
        kind: GitRepository
        name: backend-chart
        namespace: flux-system
  values:
    name: backend
    cluster: eks-production-us-east-1
    replicaCount: 2
    labels:
      app: backend
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    # livenessProbe:
    #   httpGet:
    #     path: /api/v1/api-docs
    #     port: http
    # readinessProbe:
    #   httpGet:
    #     path: /api/v1/api-docs
    #     port: http
    serviceAccount:
      create: true
      annotations: {}
      name: "backend"
    podAnnotations: {}
    podSecurityContext: {}
    securityContext: {}
    service:
      type: NodePort
      port: 5000
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:00005:certificate/157f92e5-0f11-4fb5-acf6-87d11b0a8e1c
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/healthcheck-path: /api/v1/api-docs
      hosts:
        - host: backend.production.pintv.systems
          paths:
            - path: /
    image:
      repository: 00005.dkr.ecr.us-east-1.amazonaws.com/backend
      pullPolicy: Always
      tag: 'cee69bceec25081a64bc05e683ce871a0814c0da'
    envFrom:
      - secretRef:
          name: backend-secrets