apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patches:
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: controller
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::00005:role/eksctl-eks-production-us-east-1-addon-iamserv-Role1-i7ZvstmSaRvI      
    target:
      kind: ServiceAccount
      name: "kustomize-controller"